#!/usr/bin/env node

'use strict';

const fs = require('fs');


const inputFile = process.argv[2] // Returns array of command line arguments
fs.readFile(inputFile || '', 'utf8', (err, data) => { //Read in supplied file
    if (err) {
        console.log('Incorrect file path')
    } else {
        parseCommandFile(data);

    }

});


function createBitmap(bitmap, N, M) {
    // Do not allow N X M to be grater than 250 x 250
    N = Math.min(+N, 250)
    M = Math.min(+M, 250)
    bitmap = Array.from({
            length: M
        },
        () =>
        Array.from({
                length: N
            },
            () => 'O'
        )
    );
    return bitmap;
}